import { hashSync } from 'bcrypt-ts-edge';

const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: hashSync('test123456', 10),
      role: 'admin',
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: hashSync('test123456', 10),
      role: 'user',
    },
  ],
  products: [
    {
      name: 'White hand',
      slug: 'table-white-hand',
      category: "Table",
      description: 'Minimalistic design for new spaces',
      images: [
        '/images/products/table-white-hand.jpg',
        '/images/products/table-white-hand.jpg',
      ],
      price: 59.99,
      brand: 'Irreverent',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Elegant shape',
      slug: 'lamp-elegant-shape',
      category: "Lamp",
      description: 'For innovation and new spaces',
      images: [
        '/images/products/lamp-manikin.jpg',
        '/images/products/lamp-manikin.jpg',
      ],
      price: 85.9,
      brand: 'Irreverent',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'Black dice',
      slug: 'chair-black-dice',
      category: "Chair",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        '/images/products/chair-black-dice.jpg',
        '/images/products/chair-black-dice.jpg',
      ],
      price: 99.95,
      brand: 'Irreverent',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Deadpool at home',
      slug: 'cutler-deadpool-at-home',
      category: "Cutler",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        '/images/products/cutler-deadpool.jpg',
        '/images/products/cutler-deadpool.jpg',
      ],
      price: 39.95,
      brand: 'Irreverent',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Black balls',
      slug: 'table-black-balls',
      category: "table",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        '/images/products/table-black-balls.jpg',
        '/images/products/table-black-balls.jpg',
      ],
      price: 79.99,
      brand: 'Irreverent',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Darth Vader at home',
      slug: 'cuttler-darth-vader-at-home',
      category: "Cuttler",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        '/images/products/cutler-deadpool.jpg',
        '/images/products/cutler-deadpool.jpg',
      ],
      price: 99.99,
      brand: 'Irreverent',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
